#page title
page_title                                : Recurrence

# App Info
ios_app_id                                : 1494977084

appstore_link                             : https://apps.apple.com/app/apple-store/id1494977084?mt=8 
playstore_link                            : 
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Recurrence                                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Recurrence is an app for iOS & macOS designed to help you track all the repeating tasks in your life. Perfect for tracking chores, bill payment, renewals, and so much more!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

your_name                                 : Shayes Apps LLC                             
your_link                                 : https://www.shayesapps.com                     
your_city                                 :                                 
email_address                             : support@shayesapps.com
facebook_username                         : shayesapps                                         
instagram_username                        : 
twitter_username                          : shayesapps
github_username                           : 
youtube_username                          :

features                                  :

  - title                                 : Tracking
    description                           : Track all of your recurring items
    fontawesome_icon_name                 : star
    
  - title                                 : Notifications
    description                           : Receive customizable notifications before/after your due dates
    fontawesome_icon_name                 : dot-circle

  - title                                 : Multiple Device Support
    description                           : Available for iOS & macOS device with seamless syncing
    fontawesome_icon_name                 : sync

  - title                                 : Categories
    description                           : Sort your items into customizable lists
    fontawesome_icon_name                 : list

  - title                                 : Notes
    description                           : Attach notes to items for easy reference
    fontawesome_icon_name                 : adjust
  
  - title                                 : Completion History
    description                           : See a full list of your past completions
    fontawesome_icon_name                 : history



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
theme: jekyll-theme-cayman