page_title                                : Recurrence

ios_app_id                                : 1494977084
ios_app_country                           : us

appstore_link                             : https://apps.apple.com/app/apple-store/id1494977084
privacy_policy_link                       : https://shayesapps.com/policies
presskit_download_link                    : assets/Recurrence_Press_Kit.zip

app_icon                                  : assets/appicon.png
app_name                                  : Recurrence
app_price                                 : Free
app_description                           : An app for iOS/macOS to track the repeating tasks in your life. Perfect for chores, bill payment, and much more! Recurrence puts history at the forefront, allowing you to see when something was last done & accompanying notes.

enable_smart_app_banner                   : true

your_name                                 : Shayes Apps
your_link                                 : https://www.shayesapps.com
email_address                             : support@shayesapps.com
facebook_username                         : shayesapps
instagram_username                        : shayesapps

features                                  :

  - title                                 : Tracking
    description                           : Track all of your recurring items & see what's upcoming with a quick glance
    fontawesome_icon_name                 : star

  - title                                 : Widgets
    description                           : See items right on your Home Screen or Lock Screen
    fontawesome_icon_name                 : th-large
    
  - title                                 : Notifications
    description                           : Receive customizable notifications before and after your due dates
    fontawesome_icon_name                 : dot-circle

  - title                                 : Notes
    description                           : Attach notes to items or completions for easy reference
    fontawesome_icon_name                 : clipboard

  - title                                 : Completion History
    description                           : See a full list of your past completions for each item
    fontawesome_icon_name                 : history

  - title                                 : Siri Shortcuts
    description                           : Automate your task completions
    fontawesome_icon_name                 : magic

  - title                                 : Categories
    description                           : Sort your items into lists with customizable tags
    fontawesome_icon_name                 : list

  - title                                 : Advanced Filtering
    description                           : Filter & search your items to quickly pinpoint what you want
    fontawesome_icon_name                 : filter

  - title                                 : Multiple Device Support
    description                           : Available for iOS & macOS devices with seamless syncing
    fontawesome_icon_name                 : sync


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
